# Generated by Django 2.2.7 on 2019-11-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SungWonSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(choices=[('s', 'small'), ('m', 'midium'), ('l', 'large')], max_length=1)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
