# Generated by Django 2.2.7 on 2019-11-14 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_sungwonlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sungwonlist',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='MyApplyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_apply_apart', to='main.SungWonList')),
                ('whose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_apply_whose', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
