# Generated by Django 2.2.7 on 2019-12-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191115_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='sungwonlist',
            name='office',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
