# Generated by Django 2.2.7 on 2019-12-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sungwonlist_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='sungwonlist',
            name='flag',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1),
        ),
        migrations.AddField(
            model_name='sungwonlist',
            name='owner',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sungwonlist',
            name='trade',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
