# Generated by Django 2.2.7 on 2019-12-12 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20191211_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='sungwonlist',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
